# Generated by Django 5.1.7 on 2025-06-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cakes/')),
                ('test', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], default='Pending', max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('weight', models.CharField(choices=[('0.5', '0.5 kg'), ('1', '1 kg'), ('1.5', '1.5 kg'), ('2', '2 kg'), ('custom', 'Custom')], max_length=10, null=True)),
                ('custom_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('cake', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
            ],
        ),
    ]
